import { NextRequest, NextResponse } from "next/server";
import nodemailer from "nodemailer";

export const maxDuration = 30;

interface EmailRequest {
  to: string;
  subject?: string;
  smtp: {
    host: string;
    port: number;
    secure: boolean;
    user: string;
    pass: string;
  };
  results: Array<{
    fileName: string;
    structured: Record<string, unknown>;
  }>;
  format?: "json" | "summary";
}

function validateEmail(email: string): boolean {
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email);
}

function buildSummaryHtml(
  results: EmailRequest["results"]
): string {
  let html = `<h2 style="color:#2563eb;">Resume Batch Results</h2>
<p>Total resumes processed: <strong>${results.length}</strong></p>
<hr/>`;

  for (const r of results) {
    const s = r.structured as Record<string, unknown>;
    const contact = s.contact as Record<string, string> | undefined;
    const skills = s.skills as Array<{ name: string }> | undefined;
    const experience = s.experience as Array<{ company: string; title: string }> | undefined;

    html += `<div style="margin:16px 0;padding:12px;border:1px solid #e5e7eb;border-radius:8px;">
<h3 style="margin:0 0 8px;">${contact?.name ?? r.fileName}</h3>
<p style="color:#6b7280;margin:4px 0;">${[contact?.email, contact?.phone, contact?.location].filter(Boolean).join(" · ")}</p>
<p><strong>Skills (${skills?.length ?? 0}):</strong> ${skills?.slice(0, 10).map((sk) => sk.name).join(", ") ?? "N/A"}</p>
<p><strong>Experience (${experience?.length ?? 0}):</strong> ${experience?.slice(0, 3).map((e) => `${e.title} @ ${e.company}`).join("; ") ?? "N/A"}</p>
</div>`;
  }

  html += `<hr/><p style="color:#9ca3af;font-size:12px;">Generated by Resume Parser · ${new Date().toISOString().split("T")[0]}</p>`;
  return html;
}

export async function POST(req: NextRequest) {
  const body = (await req.json()) as EmailRequest;

  if (!body.to || !validateEmail(body.to)) {
    return NextResponse.json({ error: "Invalid recipient email" }, { status: 400 });
  }

  if (!body.smtp?.host || !body.smtp?.user || !body.smtp?.pass) {
    return NextResponse.json({ error: "SMTP configuration incomplete" }, { status: 400 });
  }

  if (!body.results?.length) {
    return NextResponse.json({ error: "No results to send" }, { status: 400 });
  }

  try {
    const transporter = nodemailer.createTransport({
      host: body.smtp.host,
      port: body.smtp.port || 587,
      secure: body.smtp.secure ?? false,
      auth: {
        user: body.smtp.user,
        pass: body.smtp.pass,
      },
    });

    const attachments: Array<{ filename: string; content: string | Buffer }> = [];

    if (body.format === "json") {
      attachments.push({
        filename: "resumes-export.json",
        content: JSON.stringify(body.results, null, 2),
      });
    }

    await transporter.sendMail({
      from: body.smtp.user,
      to: body.to,
      subject: body.subject || `Resume Batch Results (${body.results.length} resumes)`,
      html: buildSummaryHtml(body.results),
      attachments,
    });

    return NextResponse.json({ success: true, message: `Email sent to ${body.to}` });
  } catch (err) {
    return NextResponse.json(
      { error: err instanceof Error ? err.message : "Failed to send email" },
      { status: 500 }
    );
  }
}
